# O Arquivo env eh composto por um stage em um formato yml:
# Exemplo:
# Arquivo -> .env.dev.yml
# Todos os arquivos env devem estar na pasta env
# variaveis:
dynamodb_table: dev_users
NODE_ENV: dev
aws_region: sa-east-1
jwt_secret: test