service: aws-nodejs-typescript-s3

plugins:
  - serverless-esbuild
  - serverless-offline
  - serverless-dotenv-plugin
provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 128 # optional, in MB, default is 1024
  timeout: 10 # optional, in seconds, default is 6
  stage: ${opt:stage, 'dev'}
  region: sa-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource: "*"
custom:
  dotenv:
    path: .env.${opt:stage, 'dev'}.yml
  tableName: ${opt:stage, 'dev'}_users
  esbuild:
    bundle: true
    minify: true
    watch:
      pattern: ['src/**/*.ts']
      ignore: ['.esbuild', 'dist', 'node_modules', '.serverless']
package: 
  individually: true
resources:
      Resources:
        Users:
          Type: AWS::DynamoDB::Table
          Properties:
            TableName: ${self:custom.tableName}
            AttributeDefinitions:
              - AttributeName: id
                AttributeType: S
              - AttributeName: sk
                AttributeType: S
              - AttributeName: email
                AttributeType: S
            KeySchema:
              - AttributeName: id
                KeyType: HASH
              - AttributeName: sk
                KeyType: RANGE
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
functions:
  authorizerUser:
      handler: handler.authorizerUser
  registerUser:
    handler: handler.registerUser
    events:
      - http:
          path: users
          method: post
  findUser:
    handler: handler.findUser
    events:
      - http:
          path: users/{id}
          method: get
          authorizer: authorizerUser # execute this before posts.create!
  findAll:
    handler: handler.findAll
    events:
      - http:
          path: users
          method: get
  

  authenticateUser:
    handler: handler.authenticateUser
    events:
      - http:
          path: users/authenticate
          method: post
  
      


