service: aws-nodejs-typescript-s3

plugins:
  - serverless-esbuild
  - serverless-offline
  - serverless-dotenv-plugin
provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 128 # optional, in MB, default is 1024
  timeout: 10 # optional, in seconds, default is 6
  stage: ${opt:stage, 'dev'}
  region: sa-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource: "*"
custom:
  dotenv:
    path: .env.${opt:stage, 'dev'}.yml
  tableName: ${opt:stage, 'dev'}_users
  esbuild:
    bundle: true
    minify: false
    watch:
      pattern: ['src/**/*.ts']
      ignore: ['.esbuild', 'dist', 'node_modules', '.serverless']
package: 
  individually: true
resources:
      Resources:
        Users:
          Type: AWS::DynamoDB::Table
          Properties:
            TableName: ${self:custom.tableName}
            AttributeDefinitions:
              - AttributeName: id
                AttributeType: S
              - AttributeName: sk
                AttributeType: S
            KeySchema:
              - AttributeName: id
                KeyType: HASH
              - AttributeName: sk
                KeyType: RANGE
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
        GatewayResponseDefault4XX:
          Type: 'AWS::ApiGateway::GatewayResponse'
          Properties:
            ResponseParameters:
              gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
              gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
            ResponseType: DEFAULT_4XX
functions:
  # Users
  authorizerUser:
      handler: handler.authorizerUser
  createUser:
    handler: handler.createUser
    events:
      - http:
          path: users
          method: post
          cors: true
  findUser:
    handler: handler.findUser
    events:
      - http:
          path: users/{user_id}
          method: get
          cors: true
          authorizer: authorizerUser #
  findAllUsers:
    handler: handler.findAllUsers
    events:
      - http:
          path: users
          method: get
          cors: true
  authenticateUser:
    handler: handler.authenticateUser
    events:
      - http:
          path: users/authenticate
          method: post
  # Tasks
  createTask:
    handler: handler.createTask
    events:
      - http:
          path: tasks
          method: post
          cors: true
          authorizer: authorizerUser 
  
  findAllUsersTasks:
    handler: handler.findAllUsersTasks
    events:
      - http:
          path: tasks
          method: get
          cors: true
          authorizer: authorizerUser 
  findByTaskStatus:
    handler: handler.findByTaskStatus
    events:
      - http:
          path: tasks/status/{status}
          method: get
          cors: true
          authorizer: authorizerUser
  updateTask:
    handler: handler.updateTask
    events:
      - http:
          path: tasks/update/{task_id}
          method: put
          cors: true
          authorizer: authorizerUser 
  deleteTask:
    handler: handler.deleteTask
    events:
      - http:
          path: tasks/delete/{task_id}
          method: delete
          cors: true
          authorizer: authorizerUser
  
  
      


